# Generated by Django 5.2.13 on 2026-05-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AC', 'AC Room'), ('NON_AC', 'Non-AC Room'), ('DELUXE', 'Deluxe Suite'), ('LUXURY', 'Luxury Premium')], max_length=100, unique=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('capacity', models.IntegerField(default=2)),
            ],
        ),
    ]
