# Generated by Django 5.2.13 on 2026-05-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional description for this photo', max_length=100)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.roomcategory')),
            ],
        ),
    ]
