# Generated by Django 5.2.13 on 2026-05-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='e.g., New York, Mumbai', max_length=100)),
                ('room_type', models.CharField(choices=[('AC', 'AC Room'), ('NON_AC', 'Non-AC Room'), ('DELUXE', 'Deluxe Suite'), ('LUXURY', 'Luxury Premium')], max_length=10)),
                ('quote', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
